<?php
/**
 * Created by PhpStorm.
 * User: edoardocarpentiero
 * Date: 2019-03-22
 * Time: 12:08
 */

use PHPUnit\Framework\TestCase;

require_once(dirname(__DIR__,2).'\IGES\Application Layer\GestioneCaricoDidattico\GestioneCaricoDidattico.php');

class UnitTestingGCD extends TestCase
{
    protected $ges;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ges=new GestioneCaricoDidattico();
        syslog(LOG_INFO, 'Message');
    }

    public function testVisualizzaInsegnamentiPropostiCorretto()
    {
        $this->assertEquals(-1,$this->ges->getInsegnamentiAssociatiAlDocente("1515d166"),"STRINGA NON ALFANUMERICA");
        $this->assertEquals(-1,$this->ges->getInsegnamentiAssociatiAlDocente("151523456789"),"STRINGA Numerica non Maggiore di 11");
        $this->assertEquals(-1,$this->ges->getInsegnamentiAssociatiAlDocente("15152345678888"),"Docente Esitente");
        $this->assertEquals(-1,$this->ges->getInsegnamentiAssociatiAlDocente("-"),"Matricola Specificata");
    }

    public function testInsegnamentiAssociati(){
        $insegnamenti=$this->ges->getInsegnamentiAssociatiAlDocente("201515166");
        $this->assertNotEmpty($insegnamenti,"Insegnamenti non associati");
        $insegnamenti=$this->ges->getInsegnamentiAssociatiAlDocente("201515168");
        $this->assertEmpty($insegnamenti,"Insegnamenti associati");
    }

    public function testGetRuoloDocente(){
        
        $ruolo=$this->ges->getRuoloDocente("201515166");
        $this->assertNotEmpty($ruolo,"Nessun ruolo");
    }

    public function testGetMonteOre(){
        
        $monteOre=$this->ges->getMonteOre("201515166");
        $this->assertNotEquals("",$monteOre);

    }

    public function testVisualizzaDocentiProgrammazioneDidattica(){
        
        $docenti=$this->ges->getDocentiPrD();
        $this->assertNotEmpty($docenti,"Lista docenti vuota");
    }

    public function testVisualizzaInsegnamentiDisponibili(){
        
        $insegnamentiDisp=$this->ges->getInsegnamentiDisponibili();
        $this->assertNotEmpty($insegnamentiDisp,"Lista insegnamenti disponibili vuota");
    }

    public function testGetCaricoDidattico(){
        
        $caricoDidattico=$this->ges->getCaricoDidattico(201515172);
        $this->assertNotEquals(0,strlen($caricoDidattico),"Carico didattico non disponibile");
    }

    public function testProponiInsegnamentoDisponibileCorretto()
    {
   
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,48,0,"PROPOSTO"));
        $this->assertTrue($proposta,"Insegnamento PROPOSTO");
    }

    public function testProponiInsegnamentoDisponibileMatricolaDocenteErrata(){
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515100,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola docente non presente");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,"201515aaa",48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola docente alfanumerica");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,"-",48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola docente non specificata");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,"201515201515",48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola docente maggiore di 11");
    }

    public function testProponiInsegnamentoDisponibileMatricolaInsegnamentoErrata(){
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(10,2,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola Insegnamento presente");
        $proposta=$this->ges->proponiInsegnamento(new Associa(30,2,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola Insegnamento disponibile");
        $proposta=$this->ges->proponiInsegnamento(new Associa("a30",2,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola Insegnamento alfanumerica");
        $proposta=$this->ges->proponiInsegnamento(new Associa("-",2,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola Insegnamento non specificata");
        $proposta=$this->ges->proponiInsegnamento(new Associa(302222222223,2,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Matricola Insegnamento maggiore di 11");
    }

    public function testProponiInsegnamentoDisponibileClasseErrata()
    {
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,0,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Classe inserita minore di 1");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,4,7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Classe inserita maggiore di 3");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,"abc",7,201515166,48,0,"PROPOSTO"));
        $this->assertFalse($proposta,"Classe inserita non numerica");
    }

    public function testProponiInsegnamentoDisponibileOreTeoriaErrato()
    {
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,"-",0,"PROPOSTO"));
        $this->assertFalse($proposta,"Ore assegnate Teoria non specificate");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,"48a",0,"PROPOSTO"));
        $this->assertFalse($proposta,"Ore assegnate Teoria alfanumerica");
    }
    public function testProponiInsegnamentoDisponibileOreLabErrato()
    {
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,48,"-","PROPOSTO"));
        $this->assertFalse($proposta,"Ore assegnate Lab non specificate");
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,48,"0a","PROPOSTO"));
        $this->assertFalse($proposta,"Ore assegnata Lab alfanumerica");
    }

    public function testProponiInsegnamentoDisponibileStatoErrato()
    {
        
        $proposta=$this->ges->proponiInsegnamento(new Associa(9,2,7,201515166,48,0,"DOMANDA"));
        $this->assertFalse($proposta,"Proposta di un insegnamento non disponibile");
    }




    public function testCambiaStatoInsegnamentoPropostoDalPresidenteCorretto()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(0,$value,"Stato aggiornato in ACCETTATO");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,0,"RIFIUTATO"));
        $this->assertEquals(0,$value,"Stato aggiornato in RIFIUTATO");

    }

    public function testCambiaStatoInsegnamentoPropostoDalDocenteCorretto()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,0,"ASSEGNATO"));
        $this->assertEquals(0,$value,"Stato aggiornato in ASSEGNATO");
        $value=$this->ges->liberaAssociazioneInsegnamento(new Associa(9,1,7,201515172,40,0,"IN ATTESA"));
        $this->assertEquals(0,$value,"Stato IN ATTESA");
//        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rzizza@unisa.it","Annullamento proposta Insegnamento","L’insegnamento da lei proposto è stato rifiutato");
  //      $this->assertEquals(0,$value,"Email inoltrata");
    }

    public function testInoltraEmailErrato()
    {
        
        $value=$this->ges->inviaEmail(201515165,201515172,"-","rzizza@unisa.it","Annullamento proposta Insegnamento","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"pres@unisa.it","rzizza@unisa.it","Annullamento proposta Insegnamento","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","-","Annullamento proposta Insegnamento","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rziza@unisa.it","Annullamento proposta Insegnamento","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rzizza@unisa.it","-","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rzizza@unisa.it","rifiuto","L’insegnamento da lei proposto è stato rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rzizza@unisa.it","Annullamento proposta Insegnamento","-");
        $this->assertEquals(-1,$value,"Email non inoltrata");
        $value=$this->ges->inviaEmail(201515165,201515172,"fferrucci@unisa.it","rzizza@unisa.it","Annullamento proposta Insegnamento","Ins. rifiutato");
        $this->assertEquals(-1,$value,"Email non inoltrata");
    }


    public function testCambiaStatoInsegnamentoPropostoMatricolaDocenteErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515167,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola docente non associata all'insegnamento");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,"a201515167",40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola docente alfanumerica");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,"",40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola docente non specificata");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515167201515167,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola docente maggiore di 11 caratteri");
    }

    public function testCambiaStatoInsegnamentoPropostoMatricolaInsegnamentoErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(12,2,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola insegnamento non presente nella programmazione didattica");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(9,1,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola insegnamento non associata al docente");
        $value=$this->ges->cambiaStatoAssociazione(new Associa("a8",2,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola insegnamento alfanumerica");
        $value=$this->ges->cambiaStatoAssociazione(new Associa("-",2,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola insegnamento non specificata");
        $value=$this->ges->cambiaStatoAssociazione(new Associa("1234567892345",2,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Matricola insegnamento maggiore di 11 caratteri");
    }

    public function testCambiaStatoInsegnamentoPropostoClasseErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,0,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Classe uguale a 0");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,4,7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Classe uguale a 4");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,"-",7,201515172,40,0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Classe uguale a 4");
    }

    public function testCambiaStatoInsegnamentoPropostoStatoErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,0,"CONVALIDATO"));
        $this->assertEquals(-1,$value,"Stato CONVALIDATO");
    }

    public function testCambiaStatoInsegnamentoPropostoOreTeoriaErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,"-",0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Ore teoria non specficate");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,"40a",0,"ACCETTATO"));
        $this->assertEquals(-1,$value,"Ore teoria non specficate");

    }

    public function testCambiaStatoInsegnamentoPropostoOreLabErrato()
    {
        
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,"-","ACCETTATO"));
        $this->assertEquals(-1,$value,"Ore teoria non specficate");
        $value=$this->ges->cambiaStatoAssociazione(new Associa(8,2,7,201515172,40,"0a","ACCETTATO"));
        $this->assertEquals(-1,$value,"Ore teoria non specficate");

    }

    public function testVisualizzaInfoInsegnamentoDisponibileCorretto()
    {
        
        $value=$this->ges->getInfoDocentiInsegnamento(30,2,7);
        $this->assertNotEmpty($value,"Info insegnamenti");
    }

    public function testVisualizzaInfoInsegnamentoDisponibileMatricolaInsegnamentoErrato(){
        
        $value=$this->ges->getInfoDocentiInsegnamento("30a",2,7);
        $this->assertFalse($value,"Matricola insegnamento alfanumerica");
        $value=$this->ges->getInfoDocentiInsegnamento(13,2,7);
        $this->assertFalse($value,"Matricola insegnamento alfanumerica");
        $value=$this->ges->getInfoDocentiInsegnamento("-",2,7);
        $this->assertFalse($value,"Matricola insegnamento non specificata");
        $value=$this->ges->getInfoDocentiInsegnamento(30303030303030,2,7);
        $this->assertFalse($value,"Matricola insegnamento maggiore di 11 caratteri");
    }

    public function testVisualizzaInfoInsegnamentoDisponibileClasseErrato(){
        
        $value=$this->ges->getInfoDocentiInsegnamento(30,3,7);
        $this->assertFalse($value,"Classe non associata all'insegnamento");
        $value=$this->ges->getInfoDocentiInsegnamento(30,0,7);
        $this->assertFalse($value,"Classe minore di 1");
        $value=$this->ges->getInfoDocentiInsegnamento(30,4,7);
        $this->assertFalse($value,"Classe maggiore di 3");
        $value=$this->ges->getInfoDocentiInsegnamento(30,"a2",7);
        $this->assertFalse($value,"Classe con valore alfanumerico");
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
        $db=new Database();
        $db->connettiDB();
        $db->eseguiQuery("update myprd_testing.Associa set Matricola_Professore=201515200, status='IN ATTESA' where Matricola_Insegnamento=9 AND classe=2 AND ID_ProgDid=7 AND Matricola_Professore=201515166 AND Ore_Teoria=48 AND Ore_Lab=0");
        $db->eseguiQuery("update myprd_testing.Associa set Matricola_Professore=201515172, status='RIFIUTATO' where Matricola_Insegnamento=9 AND classe=1 AND ID_ProgDid=7 AND Matricola_Professore=201515200 AND Ore_Teoria=40 AND Ore_Lab=0");
    }


}
