<?php


use PHPUnit\Framework\TestCase;
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneCaricoDidattico\DocentePrD.php');

class DocentePrDTest extends TestCase
{

    protected $doc;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->doc=new DocentePrD("201515166","Roberto","De Prisco","rdep@unisa.it","Docente Associato PA","INF/01");
        syslog(LOG_INFO,"UnitTesting START");
    }


    public function testSetNumeroInsegnamentiSospesi()
    {

    }

    public function testGetNome()
    {

    }

    public function testGetStatusCarico()
    {

    }

    public function testGetEmail()
    {

    }

    public function testSetCognome()
    {

    }

    public function testGetNumeroInsegnamentiSospesi()
    {

    }

    public function testSetEmail()
    {

    }

    public function testSetSettoreScientificoDisciplinare()
    {

    }

    public function testGetSettoreScientificoDisciplinare()
    {

    }

    public function testGetCognome()
    {

    }

    public function testGetMatricola()
    {

    }

    public function testSetMatricola()
    {

    }

    public function testSetRuolo()
    {

    }

    public function testSetStatusCarico()
    {

    }

    public function testSetNome()
    {

    }

    public function testGetRuolo()
    {

    }
}
