// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VisualizzaProgrammazioneDidatticaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void visualizzaProgrammazioneDidattica() {
    driver.get("http://prd.altervista.org/Presentation%20Layer/index.php");
    driver.manage().window().setSize(new Dimension(912, 1040));
    driver.findElement(By.id("inputLogin")).click();
    driver.findElement(By.id("inputLogin")).sendKeys("Presidente");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".treeview:nth-child(6) span")).click();
    driver.findElement(By.linkText("Visualizza Prog. Did.")).click();
    driver.findElement(By.id("corso")).click();
    {
      WebElement dropdown = driver.findElement(By.id("corso"));
      dropdown.findElement(By.xpath("//option[. = 'Laurea']")).click();
    }
    driver.findElement(By.id("corso")).click();
    driver.findElement(By.id("anno")).click();
    {
      WebElement dropdown = driver.findElement(By.id("anno"));
      dropdown.findElement(By.xpath("//option[. = 'Anno 2']")).click();
    }
    driver.findElement(By.id("anno")).click();
  }
}
