<?php

use PHPUnit\Framework\TestCase;
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneDocenti\Docente.php');

class DocenteTest extends TestCase
{

    protected $doc;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->doc=new Docente("201515166","Roberto","De Prisco","rdep@unisa.it","Docente Associato PA","INF/01");
        $this->doc->setNumeroInsegnamentiSospesi(6);
        $this->doc->setStatusCarico(-1);
        syslog(LOG_INFO,"UnitTesting START");
    }


    public function testGetNumeroInsegnamentiSospesi()
    {
        $this->assertEquals(6,$this->doc->getNumeroInsegnamentiSospesi());
    }

    public function testSetNumeroInsegnamentiSospesi()
    {
        $this->doc->setNumeroInsegnamentiSospesi(7);
        $this->assertEquals(7,$this->doc->getNumeroInsegnamentiSospesi());
    }

    public function testGetNome()
    {
        $this->assertEquals("Roberto",$this->doc->getNome());
    }

    public function testGetStatusCarico()
    {
        $this->assertEquals(-1,$this->doc->getStatusCarico());
    }

    public function testGetEmail()
    {
        $this->assertEquals("rdep@unisa.it",$this->doc->getEmail());
    }

        public function testSetEmail()
    {
        $this->doc->setEmail("robdeprisc@unisa.it");
        $this->assertEquals("robdeprisc@unisa.it",$this->doc->getEmail());
    }

    public function testGetSettoreScientificoDisciplinare()
    {
        $this->assertEquals("INF/01",$this->doc->getSettoreScientificoDisciplinare());
    }
    public function testSetSettoreScientificoDisciplinare()
    {
        $this->doc->setSettoreScientificoDisciplinare("INF/02");
        $this->assertEquals("INF/02",$this->doc->getSettoreScientificoDisciplinare());
    }

    public function testGetCognome()
    {
        $this->assertEquals("De Prisco",$this->doc->getCognome());
    }

    public function testSetCognome()
    {
        $this->doc->setCognome("Esposito");
        $this->assertEquals("Esposito",$this->doc->getCognome());
    }

    public function testGetMatricola()
    {
        $this->assertEquals("201515166",$this->doc->getMatricola());
    }

    public function testSetMatricola()
    {
        $this->doc->setMatricola("201515100");
        $this->assertEquals("201515100",$this->doc->getMatricola());
    }

    public function testGetRuolo()
    {
        $this->assertEquals("Docente Associato PA",$this->doc->getRuolo());
    }

    public function testSetRuolo()
    {
        $this->doc->setRuolo("Docente Ordinario PO");
        $this->assertEquals("Docente Ordinario PO",$this->doc->getRuolo());
    }

    public function testSetStatusCarico()
    {
        $this->doc->setStatusCarico(1);
        $this->assertEquals(1,$this->doc->getStatusCarico());
    }

    public function testSetNome()
    {
        $this->doc->setNome("Antonio");
        $this->assertEquals("Antonio",$this->doc->getNome());
    }


}
