<?php

use PHPUnit\Framework\TestCase;
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneCaricoDidattico\InsegnamentoProgDidattica.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneProgrammazioneDidattica\Associa.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneProgrammazioneDidattica\ProgrammazioneDidattica.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneInsegnamenti\Insegnamento.php');

class InsegnamentoProgDidatticaTest extends TestCase
{

    protected $ins;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ins=new InsegnamentoProgDidattica(
            new Insegnamento("Programmazione 1","INF/01","Obbligatorio",0,20,48,"Lezione Frontale","Laurea",58),
            new Associa("Programmazione 1",2,1,"De Prisco",40,0,"IN ATTESA"),
            new ProgrammazioneDidattica(1,1,"Laurea",1,128,150,"2021-2021",1,"Draft",8));
        syslog(LOG_INFO,"UnitTesting START");
    }

    public function testGetInsegnamento()
    {
        $insegnamento=$this->ins->getInsegnamento();
        $this->assertTrue($insegnamento instanceof Insegnamento);
    }

    public function testGetAssociazione()
    {
        $status=$this->ins->getAssociazione()->getStatus();
        $this->assertEquals("IN ATTESA",$status);
        $ass=$this->ins->getAssociazione();
        $this->assertTrue($ass instanceof Associa);
    }


    public function testGetProgrammazioneDidattica()
    {
        $prog=$this->ins->getProgrammazioneDidattica();
        $this->assertTrue($prog instanceof ProgrammazioneDidattica);
    }

}
