<?php


use PHPUnit\Framework\TestCase;
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneCaricoDidattico\InsegnamentoProgDidattica.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneProgrammazioneDidattica\Associa.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneProgrammazioneDidattica\ProgrammazioneDidattica.php');
require_once(dirname(__DIR__, 2) . '\IGES\Application Layer\GestioneInsegnamenti\Insegnamento.php');

class InsegnamentoProgDidatticaTest extends TestCase
{

    protected $ins;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ins=new InsegnamentoProgDidattica(new Insegnamento(),new Associa(),new ProgrammazioneDidattica());
        syslog(LOG_INFO,"UnitTesting START");
    }

    public function testGetInsegnamento()
    {
        $this->assertEquals("");
    }

    public function testSetInsegnamento()
    {

    }

    public function testGetAssociazione()
    {

    }

    public function testSetAssociazione()
    {

    }

    public function testGetProgrammazioneDidattica()
    {

    }

    public function testSetProgrammazioneDidattica()
    {

    }
}
